# Generated by Django 3.0.4 on 2020-07-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(default='0', max_length=50)),
                ('roomtype', models.CharField(max_length=20)),
                ('roomamount', models.CharField(max_length=5)),
                ('datein', models.CharField(max_length=20)),
                ('dateout', models.CharField(max_length=20)),
            ],
        ),
    ]
