# Generated by Django 3.0.4 on 2020-09-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_problem_descript'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='problem_descript',
            new_name='ProblemReport',
        ),
        migrations.RenameField(
            model_name='problemreport',
            old_name='user_id',
            new_name='reporter_id',
        ),
    ]
